fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "Grupo6"
        sender_name: "aaron.cruz@epn.edu.ec"